// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "bs-platform/lib/es6/belt_List.mjs";

Belt_List.forEach({
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: /* [] */0
        }
      }
    }, (function (x) {
        console.log(x);
        
      }));

export {
  
}
/*  Not a pure module */
